---
- name: Update packages
  become: true
  apt:
    name: "*"
    state: latest

- name: Install essentials packages
  become: true
  package:
    name: "{{ packages }}"
    state: latest

- name: Check if disk is present
  become: true
  parted:
    device: "/dev/{{ MOUNT_DEVICE }}"
    number: 1
    state: present
    
- name: Create partition
  become: true
  filesystem:
    fstype: ext4
    dev: "/dev/{{ MOUNT_DEVICE }}1"

- name: Mount device
  become: true
  # allow_failure: true
  mount:
    fstype: ext4
    src: "/dev/{{ MOUNT_DEVICE }}1"
    path: "/mnt/{{ MOUNT_DEVICE }}1"
    state: mounted
