---
- name: Update apt cache
  apt:
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: Install nginx package
  apt:
    name: nginx
    state: present
  when: ansible_os_family == "Debian"

- name: Install nginx package
  yum:
    name: nginx
    state: present
  when: ansible_os_family == "RedHat"

- name: Copy nginx configuration
  template:
    src: templates/nginx.conf
    dest: /etc/nginx/nginx.conf
  # notify:
      #   - Restart nginx

  # handlers:
- name: Restart nginx
  service:
    name: nginx
    state: restarted
