---
  - name: Update apt cache
    apt:
      update_cache: yes
    when: ansible_os_family == "Debian"

  - name: Install HAProxy package
    apt:
      name: haproxy
      state: present
    when: ansible_os_family == "Debian"

  - name: Copy HAProxy configuration
    template:
      src: templates/haproxy.cfg
      dest: /etc/haproxy/haproxy.cfg

  - name: Restart HAProxy
    service:
      name: haproxy
      state: restarted