---
- name: Update packages
  become: true
  apt:
    name: "*"
    state: latest

- name: Install essentials packages
  become: true
  package:
    name: "{{ packages }}"
    state: latest

- name: Disable SSH password auth
  become: true
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^#PasswordAuthentication yes"
    line: "PasswordAuthentication no"
  register: sshd_config

- name: Enable passwordless sudo for "{{ username }}"
  become: true
  lineinfile:
    dest: /etc/sudoers
    regexp: "^%wheel"
    line: "{{ username }} ALL=(ALL) NOPASSWD: ALL"
    validate: "/usr/sbin/visudo -cf %s"

- name: Restart SSH daemon
  become: true
  service:
    name: sshd
    state: restarted
  when: sshd_config.changed
